import Navbar from '@/components/navbar/Navbar'
import './globals.css'

export const metadata = {
  title: 'Smart City',
  description: 'Generated by Smart City'
}

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body className="bg-lightPrimary" suppressHydrationWarning={true}>
        {children}
      </body>
    </html>
  )
}
