import './globals.css'

export const metadata = {
  title: 'Smart City',
  description: 'Generated by Smart City'
}

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>{children}</body>
    </html>
  )
}
