import './globals.css'

export const metadata = {
  title: 'Smart City',
  description: 'Generated by Smart City'
}

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body className="bg-lightPrimary" suppressHydrationWarning={true}>
        <main className="relative w-full h-screen overflow-hidden transition-all ease-in">{children}</main>
      </body>
    </html>
  )
}
